### ISSUE TITLE
Buzzer not working on CTC (Flashforge Creator clone)

### ISSUE THREAD

**Issue by tmbrns** [jetty840/Sailfish-MightyBoardFirmware#132]
In file firmware/src/MightyBoard/Motherboard/Piezo.cc, the COM0B0 bit in the TCCR0A register is not being set when Timer 0 is used.  This is because the preprocessor directive on line 215 is "#if defined(BUZZER_SOFT_PWM)" instead of "#if !defined(...)".

**Comment by dcnewman** [comment]
Thanks for spotting that!  That's some code changes I've made as part of the Azteeg X3 port but have not yet tested on the mightyboards.  (And as such hasn't been released yet in an "official" release.)

**Comment by dcnewman** [comment]
Fixed in commit 003edd7ddc405d81d9ea88bf5e490d1900b7a922.  Thanks!  I hadn't yet tried this change on rev E electronics.  Had tried it on rev G.
