### ISSUE TITLE
Dual extrusion problem (Flashforge Creator Pro)

### ISSUE THREAD

**Issue by Ando25** [jetty840/Sailfish-MightyBoardFirmware#133]
Hello!

First of all I wanna say thank you for the awesome job you’ve done.  The new features in the new firmware are pretty nice when you only use a single extruder. I have a Flashforge Creator Pro with Dual Extruders. 

Recently I wanted to calibrate my Dual Extruder via ReplicatorG 40r30 and the scrip “FlashForge Creator Dual Nozzle Calibration.gcode” after the guidelines mentioned in the Sailfish documentary. With the newest Sailfish firmware (ff_creatorx-2560-Sailfish-v7.7.0-r1591.hex) I am unable to run a calibration because of a problem with the offset during tool change. With firmware (ff_creatorx-2560-Sailfish-v7.7.0-r1416.hex) everything’s just fine as I was used to it.

Dual extrusion with my Flashforge Creator Pro and the newest Sailfish firmware isn’t possible.

Here some pictures, first pictures with old firmware, last pictures with the newest.
![dsc_1829](https://cloud.githubusercontent.com/assets/13303688/8639635/81208aac-28e0-11e5-9736-38d6e330df5f.jpg)
![dsc_1822](https://cloud.githubusercontent.com/assets/13303688/8639636/893da8f0-28e0-11e5-8190-d5a33e3a62f3.jpg)
![dsc_1827](https://cloud.githubusercontent.com/assets/13303688/8639639/8fb2e52e-28e0-11e5-865e-b2aed959b91a.jpg)
![dsc_1828](https://cloud.githubusercontent.com/assets/13303688/8639640/90f147e6-28e0-11e5-8df6-01ae43034cec.jpg)

**Comment by dcnewman** [comment]
Thanks very much for reporting this.  There was some experimental code which I plain forgot about and should have commented out before that build.  It was code to effect the tool change motion as soon as the change tool command is received.  With MBI-style dualstusion, the tool change motion is added as a delta to the next move command.  That in turn can perturb the slope of the next move command.  Thus, people are supposed to know that immediately after a tool change, the slicer should generate a motion with no X or Y component.  This experimental change is aimed at lifting that restriction.  We've already done something in GPX as well to address this.   That said, this experimental change should have been commented out and wasn't.

I've commented out the change, tested, and uploaded r1592 to the release site.  However, it will take upwards of a couple of hours until it becomes visible owing to the web server caching which yolasite.com does.

Again, thank you very much for reporting this.
