### ISSUE TITLE
Additional localizations

### ISSUE THREAD

**Issue by Dogm** [jetty840/Sailfish-MightyBoardFirmware#137]
Is need to add new language (Russian)?
I plane test and can publish localization file if need...

**Comment by dcnewman** [comment]
If you're willing to add Russian, that would be great.  However, I doubt the LCD screen supports Cyrillic.  At least not the ones we see here in the West.

**Comment by Dogm** [comment]
Will see =)
it is possible only if no need rebuild/rewrite firmware for LCD (i don't want going there...)

**Comment by Dogm** [comment]
Plane:
1) default build platform=wanhao_dup4 - done
2) write to chip (over icsp) - done
3) trying translations: - queued
3.1) cyrilic symbols - ?
3.2) translit symbols - ?

**Comment by Dogm** [comment]
cyrilic test fail
https://monosnap.com/file/LOe0BbVgqj0ffww5pePTpekJVrMF3a

**Comment by Dogm** [comment]
heh... seem so... need unsolder and rewrite chip rom with Russian symbols >)

**Comment by Dogm** [comment]
translit - looks disgusting

**Comment by Dogm** [comment]
found symbols (not tryed yet)
https://yadi.sk/d/XzcDSzzHiLiDr
later will try (need buy PLS-16 and PBS-16)

**Comment by Dogm** [comment]
Hmm...
after inspect code for Mightyboard i found LiquidCrystalSerial libriary
maybe just make special firmware which can write special characters table for needed localization?

**Comment by dcnewman** [comment]
You only get 8 special characters.  Looks like you can have 16, but not all the modules used actually seem to support 16.  If you put a symbol into position 8 you get the one in position 0.  I.e., you get index % 8.

**Comment by Dogm** [comment]
what do you think about this?
https://github.com/mk90/LiquidCrystalRus

**Comment by dcnewman** [comment]
It might work assuming there's available code space to fit it in. On a printer with an ATmega 2560, it should fit.  On one with a 1280, it may not.  Hard to say without trying.

**Comment by Dogm** [comment]
i think this is bad idea for 1280 beacuse used Utf-8 (extra bytes for symbol code-page)
even if code size is enough - texts with custom codepage can be huge 8(

**Comment by Dogm** [comment]
utf-8 mode fail =)
https://monosnap.com/file/fHLk96TDj9IKBiNudQvrK3KdkG9B2d
think no matter codepage...

**Comment by Dogm** [comment]
hmm need to inspect
http://www.hobbytronics.co.uk/datasheets/HD44780.pdf

**Comment by Dogm** [comment]
unfortunately impossible to make localization without replacement of LCD
8(
