### ISSUE TITLE
PSU.cc many times

### ISSUE THREAD

**Issue by Dogm** [jetty840/Sailfish-MightyBoardFirmware#140]
Hi, why config "platforms.py" in many configurations contain copy of "PSU.cc"?

**Comment by dcnewman** [comment]
It likely can be removed.  Was an old source file that served no purpose and we removed at some point but then didn't remember to remove from platforms.py

**Comment by Dogm** [comment]
ok, i think this same as part of need some code refactoring/systematisation...
