### ISSUE TITLE
Have a short filament load before unload

### ISSUE THREAD

**Issue by zapta** [jetty840/Sailfish-MightyBoardFirmware#159]
On my stock Flashforge creator pro, the unload filament function doesn't work well, (filament is not released)  unless if I first load a little bit before unloading it, as if it need to be primed or something.

This feature request is for having the filament unload operation to first push the filament in a little bit before pulling it out.

**Comment by dcnewman** [comment]
Closing as "will not implement".  This suggestion comes up from time to time on the lists.  However it has a very serious problem which makes it a "no go": users from time to time have the filament break off inside the feed block or right at the entrance to the feedblock.  When that happens, the last thing that should happen is for the unload action to attempt to feed the filament in for a few millimeters.  So doing may then advance the broken filament end past the pinch gear.   And new users may be unaware that that is what the unload does -- advance a few mm and then retract it.

If you want this for your printer, write a gcode script to do it, convert it to x3g, and keep it on an SD card with other utilities.

Suggestions are welcome but they are best floated on the Sailfish firmware mailing list (jettyfirmware@groups.google.com).
