### ISSUE TITLE
How can I change the  preferences onboard through the file on SD card？

### ISSUE THREAD

**Issue by AlanQiu-914** [jetty840/Sailfish-MightyBoardFirmware#177]
They say：Ability to save and restore the bot's internal settings -- onboard preferences -- to an SD card. Backup your bot's settings or quickly transfer them to another bot.
pls teach me，how to do that，what‘s form the file will in？

**Comment by dcnewman** [comment]
Please consult the documentation, [http://www.sailfishfirmware.com/doc/index.html]( http://www.sailfishfirmware.com/doc/index.html).
