### ISSUE TITLE
Use B extruder as primary

### ISSUE THREAD

**Issue by nicoco007** [jetty840/Sailfish-MightyBoardFirmware#186]
I have an old MightyBoard Rev H with blown circuitry next to the A extruder output which prevent the hotend from receiving power. However, the B extruder ouput still works. Is there any way I could build Sailfish to use the B extruder by default instead of A?

**Comment by dnewman-polar3d** [comment]
Yes, you would just swap all two heater pin assignments between the two extruders in the Configuration.hh file (motherboard/boards/mighty_two/Configuration.hh).  Then rebuild the firmware -- not an easy task -- then install it.  Hook the extruder's heater wiring to the B extruder's and you're then good to go.

See [https://github.com/dcnewman/Ubuntu-Sailfish-VM](https://github.com/dcnewman/Ubuntu-Sailfish-VM) for some virtual machines you may be able to use to set up a toolchain with which to compile the firmware.

**Comment by nicoco007** [comment]
Alright, I'll give it a shot. Thanks!

**Comment by nicoco007** [comment]
I switched all the A/B combinations in the configuration file, build it in one of your VMs, and it works like a charm! Thank you very much for your help!

**Comment by dnewman-polar3d** [comment]
Congrats!  And thanks for the followup.  It is appreciated.
