### ISSUE TITLE
add manual speedup like in ultimaker?

### ISSUE THREAD

**Issue by TraxXavier** [jetty840/Sailfish-MightyBoardFirmware#198]
add manual speedup like in ultimaker?
Is that possible?
it would be a great feature

**Comment by dcnewman** [comment]
This feature has been in Sailfish for quite some time; possibly before Marlin.  (I don't recall offhand.)
[Please see this page of the Sailfish documentation for details.](http://www.sailfishfirmware.com/doc/ui-print-monitor-menu.html#x15-180003.4.4)
